
import type { Metadata } from "next";
import "./globals.css";
import { ThemeContextProvider } from "@/styles/ThemeContext";
import { LocalizationWrapper } from "@/components/LocalizationWrapper";
import { Providers } from "./providers";
import { Suspense } from "react";
import { SessionErrorHandler } from "@/components/SessionErrorHandler";

export const metadata: Metadata = {
  title: "Forms",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="es">
      <body>
        <Providers>
          <ThemeContextProvider>
            <LocalizationWrapper>
              {/* 🔥 Manejador de errores de sesión con Suspense */}
              <Suspense fallback={null}>
                <SessionErrorHandler />
              </Suspense>
              {children}
            </LocalizationWrapper>
          </ThemeContextProvider>
        </Providers>
      </body>
    </html>
  );
}