
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeContextProvider } from "@/styles/ThemeContext";
import { LocalizationWrapper } from "@/components/layout/wrappers/LocalizationWrapper";
import { Suspense } from "react";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v16-appRouter";
import { SessionErrorHandler } from "@/components/layout/wrappers/SessionErrorHandler";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Forms",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  // `data-scroll-behavior`: globals.css declara `scroll-behavior: smooth`.
  // Next 16 ya no lo neutraliza en las transiciones de ruta, así que sin este
  // atributo la navegación haría scroll-to-top animado en vez de instantáneo.
  return (
    <html lang="es" className={inter.variable} data-scroll-behavior="smooth">
      <body className={inter.className}>
        {/*
          Emotion —el motor de estilos de MUI— inserta sus `<style>` allí donde
          se usa el componente. En el servidor eso caía dentro del `<body>`,
          justo antes del primer componente con estilos; en el cliente Emotion
          los pone en el `<head>`. Los dos árboles no coincidían y React
          abortaba la hidratación: el error decía esperar `<Suspense>` y
          encontrar `<style data-emotion="css-global ...">`.

          `AppRouterCacheProvider` es la integración oficial de MUI para el App
          Router: usa `useServerInsertedHTML` para mandar esos estilos al
          `<head>` durante el streaming, de modo que servidor y cliente pintan
          el mismo árbol.
        */}
        <AppRouterCacheProvider options={{ key: "mui" }}>
          <ThemeContextProvider>
            <LocalizationWrapper>
              {/* 🔥 Manejador de errores de sesión con Suspense */}
              <Suspense fallback={null}>
                <SessionErrorHandler />
              </Suspense>
              {children}
            </LocalizationWrapper>
          </ThemeContextProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}