"use server"

import { API_BASE_URL } from "../constants";
import { getAuthHeaders } from "./helpers";

export type DataSourceType = 
  | "area" 
  | "superintendencia" 
  | "trabajador" 
  | "gerencia" 
  | "cargo" 
  | "equipo"
  | "vicepresidencia"
  | "supervisor";

  interface BackendItem {
  nombre?: string;
  name?: string;
  nomina?: string;
}


const VICEPRESIDENCIAS = [
  "Presidencia Ejecutiva",
  "VICEPRESIDENCIA CORPORATIVA",
  "VICEPRESIDENCIA DE DESARROLLO DE PROYECTOS",
  "VICEPRESIDENCIA DE FINANZAS",
  "VICEPRESIDENCIA DE OPERACIONES"
];

const GERENCIAS = [
  "GERENCIA CORPORATIVA",
  "GERENCIA DE COMERCIALIZACIÓN Y SERVICIOS",
  "GERENCIA DE MEDIO AMBIENTE",
  "GERENCIA DE RECURSOS HUMANOS Y SERVICIOS DE PERSONAL",
  "GERENCIA DE RELACIONES COMUNITARIAS",
  "GERENCIA DE SEGURIDAD INDUSTRIAL",
  "GERENCIA DE SERVICIOS DE TRANSPORTE Y AVIACIÓN",
  "GERENCIA DE PROYECTOS",
  "GERENCIA DE FINANZAS",
  "GERENCIA DE TI Y DESARROLLO DEL NEGOCIO",
  "GERENCIA DE MANTENIMIENTO MINA",
  "GERENCIA DE MANTENIMIENTO PLANTA",
  "GERENCIA DE OPERACIONES MINA",
  "GERENCIA DE OPERACIONES PLANTA"
];

const SUPERINTENDENCIAS = [
  "SUPERINTENDENCIA DE ADQUISICIONES",
  "SUPERINTENDENCIA DE RELACIONES INSTITUCIONALES",
  "SUPERINTENDENCIA DE RELACIONES PÚBLICAS",
  "GERENCIA CORPORATIVA",
  "SUPERINTENDENCIA DE ALMACENES Y CONTROL DE INVENTARIOS",
  "SUPERINTENDENCIA DE EXPORTACIONES",
  "SUPERINTENDENCIA DE GESTION COMERCIAL",
  "SUPERINTENDENCIA DE LOGÍSTICA",
  "SUPERINTENDENCIA DE MANEJO DE MATERIALES",
  "SUPERINTENDENCIA DE MEDIO AMBIENTE",
  "SUPERINTENDENCIA DE CAMPAMENTO",
  "SUPERINTENDENCIA DE RECURSOS HUMANOS",
  "SUPERINTENDENCIA SÉNIOR DE SALUD",
  "SUPERVISIÓN SENIOR DE SEGURIDAD FÍSICA",
  "SUPERINTENDENCIA DE DESARROLLO SOSTENIBLE Y RELACIONES COMUNITARIAS",
  "SUPERINTENDENCIA DE SEGURIDAD INDUSTRIAL",
  "SUPERINTENDENCIA DE SERVICIOS DE AVIACIÓN",
  "SUPERINTENDENCIA DE SERVICIOS DE TRANSPORTE DE PERSONAL",
  "SUPERINTENDENCIA ADMINISTRATIVO DE OPERACIONES",
  "SUPERINTENDENCIA DE INGENIERÍA PLANTA",
  "SUPERINTENDENCIA DE CONTABILIDAD",
  "SUPERINTENDENCIA DE IMPUESTOS",
  "SUPERINTENDENCIA DE PLANIFICACIÓN FINANCIERA (FP&A)",
  "SUPERINTENDENCIA DE DESARROLLO DEL NEGOCIO",
  "SUPERINTENDENCIA DE TI",
  "SUPERINTENDENCIA DE TO",
  "SUPERVISIÓN DE SEGURIDAD DE LA INFORMACIÓN (CISO)",
  "SUPERINTENDENCIA SÉNIOR DE MANTENIMIENTO MINA",
  "SUPERINTENDENCIA DE MANTENIMIENTO - ELÉCTRICO E INSTRUMENTACIÓN PLANTA",
  "SUPERINTENDENCIA DE MANTENIMIENTO - INGENIERÍA DE CONFIABILIDAD",
  "SUPERINTENDENCIA DE MANTENIMIENTO - MEC. PLTA. CHANCADO, MOLIENDA Y LUBRICACIÓN",
  "SUPERINTENDENCIA DE MANTENIMIENTO - MEC. PLTA. FLOT., FILTROS, TALLER GRAL. Y RH",
  "SUPERINTENDENCIA DE MANTENIMIENTO - PLANIFICACIÓN",
  "SUPERINTENDENCIA DE INGENIERÍA MINA",
  "SUPERINTENDENCIA DE OPERACIONES MINA",
  "SUPERINTENDENCIA DE SERVICIOS DE EXPLORACIÓN",
  "SUPERVISIÓN DE ENTRENAMIENTO MINA",
  "SUPERINTENDENCIA DE GESTIÓN DE RELAVES Y SERVICIOS AUXILIARES",
  "SUPERINTENDENCIA DE OPERACIONES PLANTA",
  "SUPERINTENDENCIA DE SERVICIOS TÉCNICOS",
  "GERENCIA DE OPERACIONES PLANTA"
];

const SUPERVISORES = [
  "ACHÁ RUIZ MARCOS ROBERTO - ESPECIALISTA DE COMEDOR Y ALIMENTOS",
  "ADUANA ROCABADO OSCAR - SUPERVISOR DE MANTENIMIENTO",
  "AGUAYO ROJAS VICTOR HUGO - PLANIFICADOR SÉNIOR DE MANTENIMIENTO",
  "ALBA URQUIZO FERNANDO JUSTO - SUPERVISOR DE OPERACIONES AÉREAS",
  "ALI SALGADO JHONNY AGUSTIN - SUPERVISOR DE MANTENIMIENTO",
  "ALIAGA RODRIGUEZ MARIO ALBERTO - SUPERINTENDENTE DE OPERACIONES MINA",
  "ANAYA RODRIGUEZ CRISTHIAN FRANKLIN - SUPERVISOR DE DISEÑO Y CONSTRUCCIÓN",
  "ANDRADE LANZA WILDER ELOY - SUPERVISOR SÉNIOR DE CAPACITACIÓN",
  "ARAMAYO QUIROGA CARLOS ANDRES - SUPERVISOR DE SERVICIOS Y PROGRAMAS DE SALUD",
  "ARANDIA COCA MARCO ANTONIO - SUPERVISOR DE MANTENIMIENTO - MOLIENDA",
  "AYALA VENEROS DOUGLAS MAURICIO - SUPERINTENDENTE DE SERVICIOS DE TRANSPORTE DE PERSONAL",
  "AYARACHI FERNANDEZ ORLANDO - PLANIFICADOR SÉNIOR DE MINA A CORTO PLAZO",
  "AZURDUY ROSSEL VLADIMIR PEDRO - SUPERVISOR DE DESARROLLO SOSTENIBLE",
  "BALDERRAMA HINOJOSA JUAN CARLOS - COORDINADOR GENERAL DE MANTENIMIENTO DE VEHÍCULOS Y EQUIPOS MÓVILES",
  "BALDERRAMA ZÁRATE BORIZ MARCELO - SUPERVISOR DE SERVICIOS DE EXPLORACIÓN",
  "BALLADARES ROCHA SAUL RAMIRO - SUPERVISOR DE MANTENIMIENTO",
  "BASILIO TICONA CORNELIO YECID - RESPONSABLE DE ENTRENAMIENTO MINA",
  "BASTUARDO MARIACA MAX NOEL - SUPERINTENDENCIA SÉNIOR DE MANTENIMIENTO MINA",
  "BELTRÁN RIOS CLAUDIA XIMENA - SUPERVISOR DE REPORTES Y CUMPLIMIENTO",
  "CABRERA MAMANI RUBEN RODY - METALURGISTA DE PROCESO",
  "CALCINA CALIZAYA EFRAÍN - SUPERVISOR DE SEGURIDAD FÍSICA",
  "CALIZAYA MENA MIKAELA LISSETTE - SUPERVISOR DE ADMINISTRACIÓN DE RECURSOS HUMANOS",
  "CAMARGO TICONA ARMANDO RICARDO - SUPERINTENDENTE DE GESTIÓN COMERCIAL",
  "CAMATA QUISPE EDILBER - SUPERVISOR DE MANTENIMIENTO",
  "CAPURATA FLORES OVIDIO - SUPERINTENDENTE DE MANTENIMIENTO",
  "CARBALLO RIVERO ROBERTO ALCIDES - ANALISTA SÉNIOR DE EXPORTACIONES",
  "CARRASCO FLORES RAUL PEDRO - SUPERVISOR DE MANTENIMIENTO",
  "CARREÑO UZQUIANO CARLOS HUGO - SUPERINTENDENTE DE GESTION DE RELAVES Y SERVICIOS AUXILIARES",
  "CARVAJAL ZABALA GUIDO MARCELO - SUPERVISOR DE MANTENIMIENTO MINA",
  "CASANOVA AGUIRRE JAIME SANTIAGO - ESPECIALISTA DE GESTIONES ADMINISTRATIVAS",
  "CASTEDO FRANCO CLAUDIO ANDRES - SUPERVISOR DE SERVICIOS AUXILIARES",
  "CASTRO RAMIREZ MARCIAL - SUPERVISOR DE CARGUÍO Y ACARREO",
  "CASTRO TORRICO MIGUEL ANGEL - SUPERVISOR DE SEGURIDAD INDUSTRIAL",
  "CAYO BARTOLOME EDWIN VIDAL - SUPERVISOR DE MANTENIMIENTO",
  "CAYO CRUZ JAIME - METALURGISTA DE PROCESO",
  "CHACON RUIZ JUAN HERNAN - SUPERVISOR DE GEOLOGÍA",
  "CHOQUE PEREIRA CALIXTO - QUÍMICO SÉNIOR",
  "CHURATA HUARACHI WILBER - GERENTE DE OPERACIONES PLANTA",
  "CLAROS MONTAÑO JUAN CARLOS - SUPERVISOR SÉNIOR DE ALMACÉN PLANTA Y COMBUSTIBLES",
  "CLAVIJO DOYNEL MARCO ANTONIO - SUPERVISOR DE CONTROL DE CALIDAD DE ALMACENES",
  "COLQUE FLORES HERIBERTO RAMIRO - SUPERVISOR DE OPERACIONES DEL SISTEMA DE CONTROL DE FLOTA",
  "CONDARCO FUENTES JHONY - SUPERVISOR DE MANTENIMIENTO",
  "COPA CALCINA EDDY EDWIN - COORDINADOR PRINCIPAL DE SISTEMAS DE AGUA",
  "CRUZ LOVERA SANTOS ADOLFO - COORDINADOR TÉCNICO OPERATIVO",
  "CRUZ RODRIGUEZ WILMERS - ANALISTA SÉNIOR DE CONFIABILIDAD",
  "DALENCE ROJAS PATRICIA BEATRIZ - SUPERINTENDENTE DE RELACIONES PÚBLICAS",
  "DURAN SAPIENCIA RONALD ABEL - SUPERVISOR DE SERVICIOS AUXILIARES",
  "ESTEPA SUAREZ CARMEN ZULEMA - SUPERVISOR DE SERVICIOS DE SALUD EXTERNA",
  "FERNANDEZ RUIZ RAMIRO - SUPERINTENDENTE DE INGENIERIA PLANTA",
  "FLORES GUTIERREZ NESTOR ROMAN - PLANIFICADOR SÉNIOR DE MANTENIMIENTO",
  "GARCIA AGREDA MARCO ANTONIO - SUPERVISOR DE MANTENIMIENTO",
  "GARNICA NUGETT ROGER SERGIO - SUPERVISOR DE CARGUÍO Y ACARREO",
  "GOMEZ ECHENIQUE JORGE JOHANN - SUPERVISOR SÉNIOR DE MANTENIMIENTO MINA - REPARACIÓN DE COMPONENTES",
  "GOMEZ VELASCO LIMBERT - SUPERVISOR DE MANTENIMIENTO",
  "GONZÁLES COPA BASILIO - COORDINADOR TÉCNICO OPERATIVO",
  "GUMUCIO LÓPEZ MIRKO GEOVANY - SUPERVISOR DE HIGIENE INDUSTRIAL",
  "GUTIERREZ TORRES LUGO VINICIO - SUPERINTENDENTE DE EXPORTACIONES",
  "HERBAS TORREZ HENRY - SUPERVISOR DE ANÁLISIS DE CONFIABILIDAD",
  "HUARACHI LEAÑO RICHARD ANTONIO - SUPERVISOR SÉNIOR DE MANTENIMIENTO MINA - SOLDADURA Y FABRICACIÓN",
  "HUARACHI MAMANI NOEL OVIDIO - SUPERVISOR DE PERFORACIÓN Y VOLADURA",
  "HUAYLLANI DELGADO JUAN DE DIOS - SUPERVISOR DE MANTENIMIENTO",
  "IMAÑA CASTRO RUBEN MARCELO - AUDITOR INTERNO",
  "JARPA CALLAHUANCA ARIEL JACINTO - JEFE DE TURNO",
  "LAZO CAYO BLADIMIR BRAULIO - SUPERVISOR SÉNIOR DE GESTIÓN DE MANTENIMIENTO DE VEHÍCULOS Y EQUIPOS MÓVILES",
  "LAZO CAYO WILSON VICENTE - SUPERINTENDENTE DE MANTENIMIENTO",
  "LEAÑO SAAVEDRA MARCO ANTONIO - SUPERVISOR DE SEGURIDAD FÍSICA",
  "LLAVE COLQUE ABRAHAM OVIDIO - COORDINADOR PRINCIPAL DE SISTEMAS DE AGUA",
  "LLORENTY SOLIZ JORGE AMED - SUPERVISOR DE EXPEDITING",
  "LOPEZ QUIROGA ROSSIO KATTIA - SUPERVISOR DE MANTENIMIENTO",
  "MAIDANA TARQUINO MARCELO - SUPERINTENDENTE ADMINISTRATIVO DE OPERACIONES",
  "MALLCU LIMACHE GUIDO - METALURGISTA DE PROCESO",
  "MAMANI DONAIRE LUCRECIO - COORDINADOR DE DRENAJE",
  "MAMANI MAMANI LUIS ORLANDO - SUPERVISOR DE CARGUÍO Y ACARREO",
  "MAMANI QUISPE ERNESTO - SUPERVISOR DE GESTIÓN DE RESÍDUOS Y ÁREAS VERDES",
  "MASSY QUIROGA NELSON - SUPERVISOR DE MEDIO AMBIENTE",
  "MENDOZA GOMEZ DIEGO ENRIQUE - SUPERINTENDENTE DE TO",
  "MERCADO CHOQUETICLLA FRANZ ARIEL - SUPERVISOR TO MINA",
  "MIRANDA OSSIO RAFAEL JUAN - JEFE DE TURNO",
  "MOHEBBI ORTUÑO VAHID FLAVIO - SUPERVISOR DE SALUD OCUPACIONAL",
  "MOLINA DAVALOS JESUS ARMANDO - SUPERVISOR DE MANEJO DE MATERIALES OPERACIONES Y ENTRENAMIENTO",
  "MOLINA MORALES VLADIMIR DAVID - SUPERVISOR DE MANTENIMIENTO",
  "MONTAÑO ORTIZ SERGIO REINALDO - SUPERVISOR SÉNIOR DE PROYECTOS Y MODIFICACIONES",
  "MOSCOSO ABRAHAM JESUS ALEJANDRO - SUPERVISOR DE TESORERÍA Y CUENTAS POR PAGAR",
  "MUÑOZ ARANDIA ERICK RICARDO - SUPERVISOR DE MANTENIMIENTO",
  "NAVAJAS FLORES RENE GONZALO - SUPERVISOR SÉNIOR DE SEGURIDAD FÍSICA",
  "NAVARRO CALDERÓN DANIEL IVÁN - SUPERVISOR DE MANTENIMIENTO MINA - PLANIFICACIÓN, PROGRAMACIÓN Y CONFIABILIDAD",
  "NAVARRO LOROÑO JULIO DAVID - SUPERINTENDENTE DE MANTENIMIENTO",
  "NUÑEZ MOLINA MARCELO MAURICIO - SUPERVISOR DE RESPONSABILIDAD SOCIAL EXTERNA",
  "OJITO ESTRADA REMBERTO - SUPERINTENDENTE DE MANEJO DE MATERIALES",
  "ORELLANA LLANOS ARIEL ISAAC - SUPERVISOR DE CONTROL DE INVENTARIOS",
  "OROSCO ARANCIBIA JUAN CARLOS - SUPERVISOR DE CARGUÍO Y ACARREO",
  "OSSIO MEZA EVANS - SUPERVISOR DE MANTENIMIENTO MINA",
  "OSUNA VACAFLOR JOSE DANIEL - SUPERVISOR SÉNIOR DE CAMPAMENTO",
  "PACO RAMOS ERICK MIROSLAV - SUPERVISOR DE MANTENIMIENTO",
  "PAUCARA HILARI DIONISIO - PLANIFICADOR SÉNIOR DE MANTENIMIENTO",
  "PEREZ BERNA GUALBERTO - SUPERVISOR GEOTECNISTA",
  "PEREZ MONDACA CARLOS ALBERTO - SUPERVISOR DE APLICACIONES DE TI",
  "PEREZ ROMERO FRANZ REYNALDO - SUPERVISOR ELÉCTRICO DE SEGURIDAD INDUSTRIAL-EMERGENCIAS",
  "POMA CRUZ DAVID RENE - SUPERVISOR SÉNIOR DE PROYECTOS Y MODIFICACIONES",
  "PONCE ANTEQUERA ALAIN ROLANDO - INGENIERO SÉNIOR DE CONFIABILIDAD ELÉCTRICA",
  "POQUECHOQUE MENESES JHONNY - PLANIFICADOR SÉNIOR DE MANTENIMIENTO",
  "QUINTEROS SAUCEDO ROBERTO - PLANIFICADOR SÉNIOR DE MANTENIMIENTO",
  "QUISPE CASTRO CRISTIAN - SUPERVISOR SÉNIOR DE GESTIÓN DE RECURSOS HUMANOS",
  "QUISPE CAYO GERMÁN GILBERTO - COORDINADOR TÉCNICO OPERATIVO",
  "QUISPE RAMOS EUSEBIO - SUPERVISOR SERVICIOS AUXILIARES",
  "QUISPE RAMOS SANTOS JAVIER - COORDINADOR DE OPERACIONES DE AERÓDROMO, ASEO Y MANTENIMIENTO PISTA",
  "QUISPE SALVATIERRA MARIN - COORDINADOR DE DRENAJE",
  "QUISPE VALDA ELIAS - COORDINADOR TÉCNICO OPERATIVO",
  "RAMIREZ MENDEZ VICTOR HUGO - SUPERVISOR ENCARGADO DE REPARACIÓN DE COMPONENTES MANTENIMIENTO MINA",
  "RAMIREZ RIVEROS RUPERTO JUAN - ANALISTA SÉNIOR DE CONFIABILIDAD",
  "RAMIREZ VALVERDE DELIO - SUPERVISOR DE RELACIONES COMUNITARIAS",
  "RAMOS COLQUE AUDO - SUPERVISOR DE SERVICIOS E INFRAESTRUCTURA",
  "RAMOS GORDILLO RENZO MARTIN - SUPERVISOR DE PROYECTOS Y MODIFICACIONES",
  "RAMOS MAYORGA MARIN - JEFE DE TURNO",
  "REYES ARISPE GUSTAVO JAVIER - SUPERINTENDENTE DE DESARROLLO DEL NEGOCIO",
  "RIVERA ARZABE ANDRÉS CRISTIAN - SUPERVISOR DE DESARROLLO ORGANIZACIONAL",
  "ROCA FERNANDEZ RAIMUNDO - SUPERVISOR DE MANTENIMIENTO AERONÁUTICO",
  "ROCHA CHUGAR GROVER ANGEL - SUPERVISOR DE TOPOGRAFIA",
  "RODRIGUEZ ARCE ANTONIO - SUPERVISOR SENIOR DE PERFORACIÓN Y VOLADURA",
  "RODRIGUEZ CALDERÓN JAIME RAMIRO - SUPERINTENDENTE DE PLANIFICACIÓN FINANCIERA (FP&A)",
  "RODRIGUEZ TAPIA ALEJANDRO - SUPERVISOR DE SEGURIDAD INDUSTRIAL",
  "RUBIN DE CELIS CANDIA MIGUEL MARTIN - SUPERINTENDENTE DE MANTENIMIENTO",
  "SAAVEDRA ANTEZANA FERNANDO ANTONIO - SUPERINTENDENTE DE SERVICIOS TECNICOS",
  "SALVATIERRA BAUTISTA OSCAR - SUPERVISOR OPERATIVO DE MANTENIMIENTO CAMPAMENTO",
  "SÁNCHEZ RIVERA LIMBERT - QUÍMICO SÉNIOR",
  "SEMPÉRTEGUI VELASCO GUSTAVO FERNANDO - QUÍMICO SÉNIOR",
  "SILES MUÑOZ HUMBERTO PABLO - SUPERVISOR SÉNIOR DE RELACIONES LABORALES",
  "SORIA CONDORI MARCO ANTONIO - JEFE TO PLANTA",
  "SOUKUP MANRIQUEZ LIBUSE - ESPECIALISTA DE DISPOSICIÓN DE MATERIALES",
  "TABOADA PRUDENCIO MARCELINO - JEFE DE LABORATORIO QUÍMICO",
  "TARDIO ROMAY IRMA VICENTA - SUPERINTENDENTE DE IMPUESTOS",
  "THOMPSON VELASQUEZ ERIK EDUARDO - SUPERINTENDENTE DE MANTENIMIENTO",
  "TINTAYA QUENTA JUAN ROBERTO - SUPERVISOR SÉNIOR DE MANTENIMIENTO MINA",
  "TORREZ SALDIAS GONZALO - SUPERVISOR DE IMPORTACIONES",
  "TORRICO MORALES ALEXANDER WALBY - SUPERVISOR DE MANTENIMIENTO",
  "TRUJILLO LLANO LEONARDO - SUPERVISOR SÉNIOR DE PROYECTOS Y MODIFICACIONES",
  "UNZUETA CARDOZO ALEJANDRA - ESPECIALISTA DE COMEDOR Y ALIMENTOS",
  "URIA ALANES CLAUDIA FATIMA - SUPERVISOR DE ADQUISICIONES DE BIENES",
  "URQUIDI SELICH MARIA ALEJANDRA - SUPERVISOR DE CONTABILIDAD Y CUENTAS POR COBRAR",
  "VALVERDE ROJAS JORGE - SUPERVISOR DE ALMACÉN MINA",
  "VARGAS SALAZAR MARTIN JORGE - SUPERVISOR DE MANTENIMIENTO MINA",
  "VELARDE LEON CRISTIAN HUMBERTO - SUPERVISOR DE INFRAESTRUCTURA DE TI",
  "VIDAL DIAZ SILVIA ABIGAIL - INGENIERO SENIOR DE CONTROL AVANZADO",
  "VILLAFUERTE SUAREZ BERNABE - JEFE DE TURNO",
  "VIÑOLA VARGAS JOSE LUIS - SUPERVISOR DE MANTENIMIENTO",
  "YUCRA YUCRA HAROLD ZACARIAS - SUPERVISOR DE MANTENIMIENTO",
  "ZAMORA CORTEZ LESLIE MAGDA - SUPERVISOR DE ADQUISICIONES DE SERVICIOS",
  "OTRO"
];

const ENDPOINTS: Record<DataSourceType, string> = {
  area: "/area",
  superintendencia: "/superintendencia",
  trabajador: "/trabajadores/nombres/all",
  gerencia: "/gerencias",
  cargo: "/cargos",
  equipo: "/equipos",
  vicepresidencia: "/vicepresidencias",
  supervisor: "/supervisores"
};

async function fetchFromBackend(endpoint: string): Promise<string[]> {
  try {
    const url = `${API_BASE_URL}${endpoint}`;
    console.log('Fetching from:', url);
    const headers = await getAuthHeaders();
    
    
    const response = await fetch(url, {
      method: "GET",
      headers,
      next: { revalidate: 300 }
    });

    if (!response.ok) {
      console.error(`Error fetching from ${url}: ${response.statusText}`);
      return [];
    }

    const data = await response.json();
    console.log('Raw data received:', data);
    
    if (Array.isArray(data) && data.every((item: unknown) => typeof item === 'string')) {
      console.log('Already strings, returning:', data);
      return data.filter((item: string) => item !== '');
    }
    
    if (Array.isArray(data)) {
      const result = data
        .map((item: BackendItem) => item.nombre || item.name || item.nomina || '')
        .filter((valor: string) => valor !== '');
      
      console.log('Processed result:', result);
      return result;
    }
    
    return [];
  } catch (error) {
    console.error(`Error loading data from ${endpoint}:`, error);
    return [];
  }
}

// Función especial para búsqueda
async function searchFromBackend(endpoint: string, query: string): Promise<string[]> {
  try {
    const url = `${API_BASE_URL}${endpoint}?query=${encodeURIComponent(query)}`;
    const headers = await getAuthHeaders();
    
    const response = await fetch(url, {
      method: "GET",
      headers,
      next: { revalidate: 60 }
    });

    if (!response.ok) {
      console.error(`Error searching from ${url}: ${response.statusText}`);
      return [];
    }

    const data = await response.json();
    
    if (Array.isArray(data) && data.every((item: unknown) => typeof item === 'string')) {
      return data.filter((item: string) => item !== '');
    }
    
    if (Array.isArray(data)) {
      return data
        .map((item: BackendItem) => item.nombre || item.name || item.nomina || '')
        .filter((nombre: string) => nombre !== '');
    }
    
    return [];
  } catch (error) {
    console.error(`Error searching from ${endpoint}:`, error);
    return [];
  }
}

export const fetchDataBySource = async (dataSource: DataSourceType): Promise<string[]> => {
  if (dataSource === 'vicepresidencia') {
    return VICEPRESIDENCIAS;
  }
  
  if (dataSource === 'gerencia') {
    return GERENCIAS;
  }

  if (dataSource === 'superintendencia') {
    return SUPERINTENDENCIAS;
  }

  if (dataSource === 'supervisor') {
    return SUPERVISORES;
  }

  const endpoint = ENDPOINTS[dataSource];
  
  if (!endpoint) {
    console.error(`Unknown data source: ${dataSource}`);
    return [];
  }

  return await fetchFromBackend(endpoint);
};

export const searchDataBySource = async (
  dataSource: DataSourceType, 
  query: string
): Promise<string[]> => {
  if (dataSource === 'vicepresidencia') {
    return VICEPRESIDENCIAS.filter(item => 
      item.toLowerCase().includes(query.toLowerCase())
    );
  }

  if (dataSource === 'gerencia') {
    return GERENCIAS.filter(item => 
      item.toLowerCase().includes(query.toLowerCase())
    );
  }

  if (dataSource === 'superintendencia') {
    return SUPERINTENDENCIAS.filter(item => 
      item.toLowerCase().includes(query.toLowerCase())
    );
  }

  if (dataSource === 'supervisor') {
    return SUPERVISORES.filter(item => 
      item.toLowerCase().includes(query.toLowerCase())
    );
  }

  if (dataSource === 'area') {
    return await searchFromBackend('/area/buscar', query);
  }
  
  if (dataSource === 'trabajador') {
    return await searchFromBackend('/trabajadores/buscar/autocomplete', query);
  }
  
  const endpoint = ENDPOINTS[dataSource];
  if (!endpoint) {
    console.error(`Unknown data source: ${dataSource}`);
    return [];
  }

  return await searchFromBackend(endpoint, query);
};

export const revalidateDataSource = async (dataSource: DataSourceType) => {
  try {
    const headers = await getAuthHeaders();
    
    const response = await fetch(`${API_BASE_URL}/revalidate`, {
      method: 'POST',
      headers,
      body: JSON.stringify({ dataSource }),
    });
    return response.ok;
  } catch (error) {
    console.error('Error revalidating data source:', error);
    return false;
  }
};